version: '3.8'

services:
  app:
    build: .
    ports:
      - "5004:5004"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./uploads:/usr/src/app/uploads
    environment:
      - NODE_ENV=production
    restart: unless-stopped